preprocess:
  sample_rate: 44100 # 44.1 kHz
  n_fft: 1024
  hop_length: 512
  n_mels: 64
  step_length: 0.5 # seconds of overlay
  spectrogram_width: 1.0 # seconds per spectrogram
  volume_threshold: -50 # dB, remove any examples below this threshold
  obfuscator:
    time_stretch_factors: [0.75, 1, 1.25, 1.5]
    pitch_factors: [0.6, 0.8, 1, 1.2, 1.5]
    lowpass_range: [6000, 12000]
    highpass_range: [20, 1000]
    whitenoise_range: [0.00, 0.05]
    musan_noise_range: [-5.0, 5.0]
    lowpass_frac: 0.5
    num_tones_to_add: 5
    tone_gen_frequency_range: [50, 1001]
    tone_gen_amplitude_range: [0, .5]
    tone_gen_duration_range: [0.1, 0.5]

network:
  stride: 1
  padding: 1
  pool_kernel_size: 2
  conv_layer_dims:
    - [1, 16]
    - [16, 32]
    - [32, 64]
    - [64, 128]
    - [128, 256]
    - [256, 384]
    - [384, 512]
  min_dims: [1, 1] # The tensor won't get pooled lower than these dimensions (h x w)
  num_branches: 4
  divide_and_encode_hidden_dim: 256
  embedding_dim: 128
  source_batch_size: 200 # songs per batch
  sub_batch_size: 2000 # the number of examples the cnn actually trains on at a time
  learning_rate: 0.00005
  num_epochs: 100
  alpha: 0.2

post:
  span: 0.5 # absolute value of seconds to offset positive from ground
  step: 0.01 # seconds to step each offset from -span to span
  alpha: 9.0 # constant to use in sequence similarity formula
  top_k: 10

paths:
  log_dir: "/home/james/code/sample-hunter/_data/logs"
  cache_dir: "/home/james/code/sample-hunter/_data/cache"
  musan: "/home/james/code/sample-hunter/_data/musan"

hf:
  repo_id: "samplr/songs"
  url: "https://huggingface.co/datasets/samplr/songs"
