#"global" params
sample_rate: 44100
hop_length: 512
n_fft: 1024
n_mels: 64
spec_num_sec: 1.0

# preprocess config
step_num_sec: 0.5
volume_threshold: -50 # dbfs

# obfuscator config
time_stretch_factors: [0.75, 1.0, 1.25, 1.5]
pitch_factors: [0.6, 0.8, 1.0, 1.2, 1.5]
lowpass_range: [6000, 12000]
highpass_range: [20, 1000]
musan_noise_range: [15, 30] # snr
lowpass_frac: 0.5
perturb_num_workers: 1
# musan: "./_data/musan"
musan: "/content/drive/MyDrive/sample-hunter/musan"

# train config
source_batch_size: 100
sub_batch_size: 1000
learning_rate: 0.005
num_epochs: 30
triplet_loss_margin: 1.0
tensorboard_log_dir: "/content/drive/MyDrive/sample-hunter/9-11-2025/logs"
tensorboard: "epoch"
quantize_scale: 452.1110 # fix
zero_point: 0 # fix
# cache_dir: "./_data/cache"
cache_dir: "/content/drive/MyDrive/sample-hunter/cache"
mine_strategy: "semi"

# encodernet architecture hyperparameters
kernel_stride: 1
kernel_padding: 1
pool_kernel_size: 2
conv_layer_dims:
  - [1, 16]
  - [16, 32]
  - [32, 64]
  - [64, 128]
  - [128, 256]
  - [256, 384]
  - [384, 512]
  - [512, 768]
  - [768, 896]
  - [896, 1024]
min_dims: [1, 1]
num_branches: 4
divide_and_encode_hidden_dim: 512
embedding_dim: 128